/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    faq: Faq;
    team: Team;
    testimonials: Testimonial;
    forms: Form;
    'form-submissions': FormSubmission;
    hero: Hero;
    'cta-banners': CtaBanner;
    'values-sections': ValuesSection;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    faq: FaqSelect<false> | FaqSelect<true>;
    team: TeamSelect<false> | TeamSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    hero: HeroSelect<false> | HeroSelect<true>;
    'cta-banners': CtaBannersSelect<false> | CtaBannersSelect<true>;
    'values-sections': ValuesSectionsSelect<false> | ValuesSectionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'bg') | ('en' | 'bg')[];
  globals: {
    'site-settings': SiteSetting;
    navigation: Navigation;
    footer: Footer;
    'ui-strings': UiString;
    languages: Language;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'ui-strings': UiStringsSelect<false> | UiStringsSelect<true>;
    languages: LanguagesSelect<false> | LanguagesSelect<true>;
  };
  locale: 'en' | 'bg';
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Website pages
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  /**
   * Page title
   */
  title: string;
  /**
   * URL segment (e.g., 'cleaning' for /services/cleaning). Leave empty for homepage.
   */
  slug?: string | null;
  /**
   * Parent page (leave empty for top-level pages)
   */
  parent?: (number | null) | Page;
  /**
   * Full URL path (auto-generated from parent + slug)
   */
  pathname: string;
  /**
   * Control where this page appears
   */
  visibility?: {
    /**
     * Show this page in the main navigation
     */
    showInNavigation?: boolean | null;
    /**
     * Order in navigation (lower = first)
     */
    navigationOrder?: number | null;
    /**
     * Show this page in the footer
     */
    showInFooter?: boolean | null;
    /**
     * Which footer column to display in
     */
    footerColumn?: ('company' | 'services' | 'support') | null;
    /**
     * Order in footer column (lower = first)
     */
    footerOrder?: number | null;
  };
  /**
   * Page template determines available sections and layout
   */
  template: 'home' | 'about' | 'services' | 'service' | 'contact';
  /**
   * Build your page by adding and arranging sections
   */
  sections?:
    | (
        | {
            /**
             * Select hero content from the library
             */
            hero: number | Hero;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero-section';
          }
        | {
            /**
             * Visual style of the hero
             */
            variant?: ('gradient' | 'image' | 'dark') | null;
            /**
             * Background image (only used when variant is 'Image Background')
             */
            backgroundImage?: (number | null) | Media;
            /**
             * Darkness of the overlay on the image
             */
            overlayOpacity?: ('light' | 'medium' | 'dark') | null;
            /**
             * Small text above heading (e.g., 'About Us', 'Our Services')
             */
            badge?: string | null;
            /**
             * Page heading
             */
            heading?: string | null;
            /**
             * Subtitle text below heading
             */
            subtitle?: string | null;
            /**
             * Show breadcrumb navigation
             */
            showBreadcrumbs?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'page-hero-section';
          }
        | {
            /**
             * Select values section content from the library
             */
            valuesSection: number | ValuesSection;
            /**
             * Section background style
             */
            bgVariant?: ('white' | 'light' | 'gradient' | 'dark') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'values-section';
          }
        | {
            /**
             * Section background style
             */
            bgVariant?: ('white' | 'light' | 'gradient' | 'dark') | null;
            /**
             * Small text above the heading
             */
            badge?: string | null;
            /**
             * Section heading
             */
            heading?: string | null;
            /**
             * Section subheading or description
             */
            subheading?: string | null;
            /**
             * Company values (4-6 recommended)
             */
            values?:
              | {
                  title: string;
                  description?: string | null;
                  /**
                   * Icon representing this value
                   */
                  icon?:
                    | (
                        | 'home'
                        | 'building'
                        | 'sparkles'
                        | 'brush'
                        | 'droplets'
                        | 'leaf'
                        | 'shield'
                        | 'clock'
                        | 'star'
                        | 'truck'
                        | 'heart'
                        | 'users'
                        | 'award'
                        | 'message-square'
                      )
                    | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * Number of columns on desktop
             */
            layout?: ('grid-2' | 'grid-3' | 'grid-4') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'company-values-section';
          }
        | {
            /**
             * Section background style
             */
            bgVariant?: ('white' | 'light' | 'gradient' | 'dark') | null;
            /**
             * Small text above the heading
             */
            badge?: string | null;
            /**
             * Section heading
             */
            heading?: string | null;
            /**
             * Section subheading or description
             */
            subheading?: string | null;
            mission?: {
              title?: string | null;
              /**
               * Mission statement
               */
              content?: string | null;
              /**
               * Optional image for mission card
               */
              image?: (number | null) | Media;
            };
            vision?: {
              title?: string | null;
              /**
               * Vision statement
               */
              content?: string | null;
              /**
               * Optional image for vision card
               */
              image?: (number | null) | Media;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'mission-vision-section';
          }
        | {
            /**
             * Section background style
             */
            bgVariant?: ('white' | 'light' | 'gradient' | 'dark') | null;
            /**
             * Small text above the heading
             */
            badge?: string | null;
            /**
             * Section heading
             */
            heading?: string | null;
            /**
             * Section subheading or description
             */
            subheading?: string | null;
            /**
             * Statistics to display (3-4 recommended)
             */
            stats?:
              | {
                  /**
                   * The number/value (e.g., '500+', '10K', '99%')
                   */
                  value: string;
                  /**
                   * Label describing the stat (e.g., 'Happy Clients')
                   */
                  label: string;
                  /**
                   * Color variant for this stat card
                   */
                  variant?: ('navy' | 'teal' | 'yellow' | 'white') | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * Number of columns on desktop
             */
            layout?: ('grid-2' | 'grid-3' | 'grid-4') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'stats-section';
          }
        | {
            /**
             * Section background style
             */
            bgVariant?: ('white' | 'light' | 'gradient' | 'dark') | null;
            /**
             * Small text above the heading
             */
            badge?: string | null;
            /**
             * Section heading
             */
            heading?: string | null;
            /**
             * Section subheading or description
             */
            subheading?: string | null;
            /**
             * Timeline events in chronological order
             */
            events?:
              | {
                  /**
                   * Year or date (e.g., '2020', 'Jan 2023')
                   */
                  year: string;
                  /**
                   * Event title
                   */
                  title: string;
                  /**
                   * Event description
                   */
                  description?: string | null;
                  /**
                   * Optional image for this event
                   */
                  image?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            /**
             * Alternate events left/right on desktop
             */
            alternating?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'timeline-section';
          }
        | {
            /**
             * Section background style
             */
            bgVariant?: ('white' | 'light' | 'gradient' | 'dark') | null;
            /**
             * Show section header above content
             */
            showHeader?: boolean | null;
            /**
             * Small text above the heading
             */
            badge?: string | null;
            /**
             * Section heading
             */
            heading?: string | null;
            /**
             * Section subheading
             */
            subheading?: string | null;
            /**
             * Rich text content
             */
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            /**
             * Content width/layout
             */
            layout?: ('default' | 'wide' | 'full' | 'two-columns') | null;
            /**
             * Apply typography styles (prose) to content
             */
            prose?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'rich-text-section';
          }
        | {
            /**
             * Section background style
             */
            bgVariant?: ('white' | 'light' | 'gradient' | 'dark') | null;
            /**
             * Small text above the heading
             */
            badge?: string | null;
            /**
             * Section heading
             */
            heading?: string | null;
            /**
             * Section subheading or description
             */
            subheading?: string | null;
            /**
             * Select service pages to display (3 recommended)
             */
            services?: (number | Page)[] | null;
            /**
             * Link for 'View All' button (e.g., /services). Leave empty to hide button.
             */
            viewAllHref?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'services-section';
          }
        | {
            /**
             * Section background style
             */
            bgVariant?: ('white' | 'light' | 'gradient' | 'dark') | null;
            /**
             * Small text above the heading
             */
            badge?: string | null;
            /**
             * Section heading
             */
            heading?: string | null;
            /**
             * Section subheading or description
             */
            subheading?: string | null;
            /**
             * Select specific service pages (leave empty to show all)
             */
            services?: (number | Page)[] | null;
            /**
             * Show all service pages (overrides selection above)
             */
            showAll?: boolean | null;
            /**
             * Maximum number of services to show
             */
            limit?: number | null;
            /**
             * Show service prices on cards
             */
            showPrices?: boolean | null;
            /**
             * Show feature bullets on cards
             */
            showFeatures?: boolean | null;
            /**
             * Number of columns on desktop
             */
            layout?: ('grid-2' | 'grid-3') | null;
            /**
             * Call-to-action section
             */
            cta?: {
              /**
               * Show the CTA section
               */
              show?: boolean | null;
              /**
               * Text above the button
               */
              text?: string | null;
              /**
               * Button label
               */
              buttonText?: string | null;
              /**
               * Button link
               */
              buttonHref?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'services-grid-section';
          }
        | {
            /**
             * Section background style
             */
            bgVariant?: ('white' | 'light' | 'gradient' | 'dark') | null;
            /**
             * Small text above the heading
             */
            badge?: string | null;
            /**
             * Section heading
             */
            heading?: string | null;
            /**
             * Section subheading or description
             */
            subheading?: string | null;
            /**
             * Pricing tiers (2-3 recommended)
             */
            tiers?:
              | {
                  /**
                   * Tier name (e.g., 'Basic', 'Pro', 'Enterprise')
                   */
                  name: string;
                  /**
                   * Price (e.g., '$99', 'From $199', 'Custom')
                   */
                  price: string;
                  /**
                   * Billing period (e.g., 'per visit', 'per month')
                   */
                  period?: string | null;
                  /**
                   * Short description of this tier
                   */
                  description?: string | null;
                  /**
                   * Highlight this tier as featured/popular
                   */
                  featured?: boolean | null;
                  /**
                   * Features included in this tier
                   */
                  features?:
                    | {
                        feature: string;
                        id?: string | null;
                      }[]
                    | null;
                  ctaLabel?: string | null;
                  ctaHref?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'pricing-section';
          }
        | {
            /**
             * Section background style
             */
            bgVariant?: ('white' | 'light' | 'gradient' | 'dark') | null;
            /**
             * Small text above the heading
             */
            badge?: string | null;
            /**
             * Section heading
             */
            heading?: string | null;
            /**
             * Section subheading or description
             */
            subheading?: string | null;
            /**
             * Select testimonials to display
             */
            testimonials?: (number | Testimonial)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonials-section';
          }
        | {
            /**
             * Section background style
             */
            bgVariant?: ('white' | 'light' | 'gradient' | 'dark') | null;
            /**
             * Small text above the heading
             */
            badge?: string | null;
            /**
             * Section heading
             */
            heading?: string | null;
            /**
             * Section subheading or description
             */
            subheading?: string | null;
            /**
             * Select team members to display (leave empty to show all)
             */
            teamMembers?: (number | Team)[] | null;
            /**
             * Show all team members (overrides selection above)
             */
            showAll?: boolean | null;
            /**
             * Number of columns on desktop
             */
            layout?: ('grid-2' | 'grid-3' | 'grid-4') | null;
            /**
             * Show team member bios
             */
            showBio?: boolean | null;
            /**
             * Show social media links
             */
            showSocialLinks?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'team-section';
          }
        | {
            /**
             * Section background style
             */
            bgVariant?: ('white' | 'light' | 'gradient' | 'dark') | null;
            /**
             * Small text above the heading
             */
            badge?: string | null;
            /**
             * Section heading
             */
            heading?: string | null;
            /**
             * Section subheading or description
             */
            subheading?: string | null;
            /**
             * Select FAQs to display (4-6 recommended)
             */
            faqs?: (number | Faq)[] | null;
            /**
             * Call-to-action section
             */
            cta?: {
              /**
               * Show the CTA section
               */
              show?: boolean | null;
              /**
               * Text above the button
               */
              text?: string | null;
              /**
               * Button label
               */
              buttonText?: string | null;
              /**
               * Button link
               */
              buttonHref?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'faq-section';
          }
        | {
            /**
             * Section background style
             */
            bgVariant?: ('white' | 'light' | 'gradient' | 'dark') | null;
            /**
             * Small text above the heading
             */
            badge?: string | null;
            /**
             * Section heading
             */
            heading?: string | null;
            /**
             * Section subheading or description
             */
            subheading?: string | null;
            /**
             * Select the form to display
             */
            form: number | Form;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contact-form-section';
          }
        | {
            /**
             * Section background style
             */
            bgVariant?: ('white' | 'light' | 'gradient' | 'dark') | null;
            /**
             * Small text above the heading
             */
            badge?: string | null;
            /**
             * Section heading
             */
            heading?: string | null;
            /**
             * Section subheading or description
             */
            subheading?: string | null;
            /**
             * Select the contact form to display
             */
            form: number | Form;
            /**
             * Show contact information alongside the form
             */
            showContactInfo?: boolean | null;
            /**
             * Show embedded map below the section
             */
            showMap?: boolean | null;
            /**
             * Address to show on map (uses site settings if empty)
             */
            mapAddress?: string | null;
            /**
             * Show social media links in contact info
             */
            showSocialLinks?: boolean | null;
            /**
             * Layout arrangement
             */
            layout?: ('side-by-side' | 'form-only' | 'stacked') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contact-section';
          }
        | {
            /**
             * Section background style
             */
            bgVariant?: ('white' | 'light' | 'gradient' | 'dark') | null;
            /**
             * Show section header above map
             */
            showHeader?: boolean | null;
            /**
             * Small text above the heading
             */
            badge?: string | null;
            /**
             * Section heading
             */
            heading?: string | null;
            /**
             * Section subheading
             */
            subheading?: string | null;
            /**
             * Address for the map (uses site settings if empty)
             */
            address?: string | null;
            /**
             * Label to display above the map (optional)
             */
            addressLabel?: string | null;
            /**
             * Map height
             */
            height?: ('small' | 'medium' | 'large') | null;
            /**
             * Map zoom level (1-20)
             */
            zoom?: number | null;
            /**
             * Make map full width (edge to edge)
             */
            fullWidth?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'map-embed-section';
          }
        | {
            /**
             * Select CTA banner content
             */
            ctaBanner?: (number | null) | CtaBanner;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta-banner-section';
          }
      )[]
    | null;
  /**
   * Service-specific information
   */
  serviceData?: {
    /**
     * Short description for listings and cards
     */
    description?: string | null;
    /**
     * Detailed service content (WYSIWYG editor)
     */
    content?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    /**
     * Icon displayed on service cards
     */
    icon?:
      | (
          | 'home'
          | 'building'
          | 'sparkles'
          | 'brush'
          | 'droplets'
          | 'leaf'
          | 'shield'
          | 'clock'
          | 'star'
          | 'truck'
          | 'heart'
          | 'users'
          | 'award'
          | 'message-square'
        )
      | null;
    /**
     * Service image for hero and cards
     */
    image?: (number | null) | Media;
    /**
     * Starting price (e.g., 'From $99' or 'от 99 лв.')
     */
    price?: string | null;
    /**
     * Key features included in this service
     */
    features?:
      | {
          feature: string;
          id?: string | null;
        }[]
      | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Hero banner content for the homepage
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero".
 */
export interface Hero {
  id: number;
  /**
   * Visual style variant
   */
  variant?: ('default' | 'centered' | 'fullBackground') | null;
  /**
   * Small badge text above the headline
   */
  badge: string;
  /**
   * Main headline (the highlighted word will be the last word)
   */
  headline: string;
  /**
   * Word to highlight with teal background (must be contained in the headline)
   */
  highlightedWord: string;
  subheadline: string;
  primaryCta: {
    label: string;
    href: string;
  };
  secondaryCta: {
    label: string;
    href: string;
  };
  image: number | Media;
  trustBadges?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  stats: {
    rating: string;
    reviewCount: string;
    experience: string;
    experienceLabel: string;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Reusable values/about sections with stats and badges
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "values-sections".
 */
export interface ValuesSection {
  id: number;
  /**
   * Visual style variant
   */
  variant?: ('default' | 'minimal' | 'withImage') | null;
  /**
   * Small badge text above the heading
   */
  badge?: string | null;
  heading: string;
  description?: string | null;
  /**
   * CTA button text
   */
  ctaLabel?: string | null;
  /**
   * CTA button link
   */
  ctaHref?: string | null;
  /**
   * Image (used in 'With Image' variant)
   */
  image?: (number | null) | Media;
  /**
   * Value badges to display
   */
  values?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Statistics cards
   */
  stats?:
    | {
        value: string;
        label: string;
        variant?: ('navy' | 'teal' | 'teal-dark') | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Customer reviews and testimonials
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  /**
   * The testimonial text
   */
  quote: string;
  /**
   * Customer name
   */
  author: string;
  /**
   * Job title, location, or context (e.g., 'Homeowner, Brooklyn')
   */
  role?: string | null;
  /**
   * Customer photo (optional)
   */
  avatar?: (number | null) | Media;
  /**
   * Star rating
   */
  rating: '5' | '4' | '3' | '2' | '1';
  /**
   * Show on homepage
   */
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Team member profiles
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team".
 */
export interface Team {
  id: number;
  /**
   * Full name
   */
  name: string;
  /**
   * Job title
   */
  role: string;
  /**
   * Short biography
   */
  bio?: string | null;
  /**
   * Profile photo
   */
  photo: number | Media;
  /**
   * Contact email (optional)
   */
  email?: string | null;
  /**
   * Sort order (lower numbers appear first)
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Frequently asked questions
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq".
 */
export interface Faq {
  id: number;
  /**
   * The question
   */
  question: string;
  /**
   * The answer
   */
  answer: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * FAQ category for filtering
   */
  category: 'general' | 'services' | 'pricing' | 'booking';
  /**
   * Sort order (lower numbers appear first)
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Configurable forms with validation rules
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  /**
   * Form name (e.g., 'Contact Form', 'Quote Request')
   */
  title: string;
  /**
   * Text displayed on the submit button
   */
  submitButtonText?: string | null;
  /**
   * Message shown after successful submission
   */
  successMessage?: string | null;
  /**
   * Configure email notifications when form is submitted
   */
  emailNotification?: {
    /**
     * Send email notification when form is submitted
     */
    enabled?: boolean | null;
    /**
     * Email address to receive notifications
     */
    recipientEmail?: string | null;
    /**
     * Subject line for notification email
     */
    emailSubject?: string | null;
  };
  /**
   * Form fields configuration
   */
  fields: {
    /**
     * Field key (used in form data, e.g., 'firstName', 'email')
     */
    name: string;
    /**
     * Label displayed above the field
     */
    label: string;
    /**
     * Type of input field
     */
    type: 'text' | 'email' | 'tel' | 'textarea' | 'select' | 'checkbox';
    /**
     * Placeholder text inside the field
     */
    placeholder?: string | null;
    /**
     * Is this field required?
     */
    required?: boolean | null;
    /**
     * Field width in the form layout
     */
    width?: ('full' | 'half') | null;
    /**
     * Minimum character length
     */
    minLength?: number | null;
    /**
     * Maximum character length
     */
    maxLength?: number | null;
    /**
     * Regex pattern for validation (advanced)
     */
    pattern?: string | null;
    /**
     * Custom error message when validation fails
     */
    errorMessage?: string | null;
    /**
     * Options for select dropdown
     */
    options?:
      | {
          /**
           * Option value (stored in form data)
           */
          value: string;
          /**
           * Option label (displayed to user)
           */
          label: string;
          id?: string | null;
        }[]
      | null;
    id?: string | null;
  }[];
  updatedAt: string;
  createdAt: string;
}
/**
 * Call-to-action banners with background images
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cta-banners".
 */
export interface CtaBanner {
  id: number;
  /**
   * Internal name for this banner
   */
  title: string;
  headingWhite?: string | null;
  headingTeal?: string | null;
  buttonText?: string | null;
  buttonHref?: string | null;
  /**
   * Recommended: 1920x600px or larger for parallax effect
   */
  backgroundImage?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * Submitted form data
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  /**
   * The form that was submitted
   */
  form: number | Form;
  /**
   * Submitted form data (field name -> value)
   */
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * When the form was submitted
   */
  submittedAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'faq';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'team';
        value: number | Team;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'hero';
        value: number | Hero;
      } | null)
    | ({
        relationTo: 'cta-banners';
        value: number | CtaBanner;
      } | null)
    | ({
        relationTo: 'values-sections';
        value: number | ValuesSection;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  parent?: T;
  pathname?: T;
  visibility?:
    | T
    | {
        showInNavigation?: T;
        navigationOrder?: T;
        showInFooter?: T;
        footerColumn?: T;
        footerOrder?: T;
      };
  template?: T;
  sections?:
    | T
    | {
        'hero-section'?:
          | T
          | {
              hero?: T;
              id?: T;
              blockName?: T;
            };
        'page-hero-section'?:
          | T
          | {
              variant?: T;
              backgroundImage?: T;
              overlayOpacity?: T;
              badge?: T;
              heading?: T;
              subtitle?: T;
              showBreadcrumbs?: T;
              id?: T;
              blockName?: T;
            };
        'values-section'?:
          | T
          | {
              valuesSection?: T;
              bgVariant?: T;
              id?: T;
              blockName?: T;
            };
        'company-values-section'?:
          | T
          | {
              bgVariant?: T;
              badge?: T;
              heading?: T;
              subheading?: T;
              values?:
                | T
                | {
                    title?: T;
                    description?: T;
                    icon?: T;
                    id?: T;
                  };
              layout?: T;
              id?: T;
              blockName?: T;
            };
        'mission-vision-section'?:
          | T
          | {
              bgVariant?: T;
              badge?: T;
              heading?: T;
              subheading?: T;
              mission?:
                | T
                | {
                    title?: T;
                    content?: T;
                    image?: T;
                  };
              vision?:
                | T
                | {
                    title?: T;
                    content?: T;
                    image?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'stats-section'?:
          | T
          | {
              bgVariant?: T;
              badge?: T;
              heading?: T;
              subheading?: T;
              stats?:
                | T
                | {
                    value?: T;
                    label?: T;
                    variant?: T;
                    id?: T;
                  };
              layout?: T;
              id?: T;
              blockName?: T;
            };
        'timeline-section'?:
          | T
          | {
              bgVariant?: T;
              badge?: T;
              heading?: T;
              subheading?: T;
              events?:
                | T
                | {
                    year?: T;
                    title?: T;
                    description?: T;
                    image?: T;
                    id?: T;
                  };
              alternating?: T;
              id?: T;
              blockName?: T;
            };
        'rich-text-section'?:
          | T
          | {
              bgVariant?: T;
              showHeader?: T;
              badge?: T;
              heading?: T;
              subheading?: T;
              content?: T;
              layout?: T;
              prose?: T;
              id?: T;
              blockName?: T;
            };
        'services-section'?:
          | T
          | {
              bgVariant?: T;
              badge?: T;
              heading?: T;
              subheading?: T;
              services?: T;
              viewAllHref?: T;
              id?: T;
              blockName?: T;
            };
        'services-grid-section'?:
          | T
          | {
              bgVariant?: T;
              badge?: T;
              heading?: T;
              subheading?: T;
              services?: T;
              showAll?: T;
              limit?: T;
              showPrices?: T;
              showFeatures?: T;
              layout?: T;
              cta?:
                | T
                | {
                    show?: T;
                    text?: T;
                    buttonText?: T;
                    buttonHref?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'pricing-section'?:
          | T
          | {
              bgVariant?: T;
              badge?: T;
              heading?: T;
              subheading?: T;
              tiers?:
                | T
                | {
                    name?: T;
                    price?: T;
                    period?: T;
                    description?: T;
                    featured?: T;
                    features?:
                      | T
                      | {
                          feature?: T;
                          id?: T;
                        };
                    ctaLabel?: T;
                    ctaHref?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'testimonials-section'?:
          | T
          | {
              bgVariant?: T;
              badge?: T;
              heading?: T;
              subheading?: T;
              testimonials?: T;
              id?: T;
              blockName?: T;
            };
        'team-section'?:
          | T
          | {
              bgVariant?: T;
              badge?: T;
              heading?: T;
              subheading?: T;
              teamMembers?: T;
              showAll?: T;
              layout?: T;
              showBio?: T;
              showSocialLinks?: T;
              id?: T;
              blockName?: T;
            };
        'faq-section'?:
          | T
          | {
              bgVariant?: T;
              badge?: T;
              heading?: T;
              subheading?: T;
              faqs?: T;
              cta?:
                | T
                | {
                    show?: T;
                    text?: T;
                    buttonText?: T;
                    buttonHref?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'contact-form-section'?:
          | T
          | {
              bgVariant?: T;
              badge?: T;
              heading?: T;
              subheading?: T;
              form?: T;
              id?: T;
              blockName?: T;
            };
        'contact-section'?:
          | T
          | {
              bgVariant?: T;
              badge?: T;
              heading?: T;
              subheading?: T;
              form?: T;
              showContactInfo?: T;
              showMap?: T;
              mapAddress?: T;
              showSocialLinks?: T;
              layout?: T;
              id?: T;
              blockName?: T;
            };
        'map-embed-section'?:
          | T
          | {
              bgVariant?: T;
              showHeader?: T;
              badge?: T;
              heading?: T;
              subheading?: T;
              address?: T;
              addressLabel?: T;
              height?: T;
              zoom?: T;
              fullWidth?: T;
              id?: T;
              blockName?: T;
            };
        'cta-banner-section'?:
          | T
          | {
              ctaBanner?: T;
              id?: T;
              blockName?: T;
            };
      };
  serviceData?:
    | T
    | {
        description?: T;
        content?: T;
        icon?: T;
        image?: T;
        price?: T;
        features?:
          | T
          | {
              feature?: T;
              id?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq_select".
 */
export interface FaqSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  category?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team_select".
 */
export interface TeamSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  bio?: T;
  photo?: T;
  email?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  quote?: T;
  author?: T;
  role?: T;
  avatar?: T;
  rating?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  submitButtonText?: T;
  successMessage?: T;
  emailNotification?:
    | T
    | {
        enabled?: T;
        recipientEmail?: T;
        emailSubject?: T;
      };
  fields?:
    | T
    | {
        name?: T;
        label?: T;
        type?: T;
        placeholder?: T;
        required?: T;
        width?: T;
        minLength?: T;
        maxLength?: T;
        pattern?: T;
        errorMessage?: T;
        options?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  data?: T;
  submittedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero_select".
 */
export interface HeroSelect<T extends boolean = true> {
  variant?: T;
  badge?: T;
  headline?: T;
  highlightedWord?: T;
  subheadline?: T;
  primaryCta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  secondaryCta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  image?: T;
  trustBadges?:
    | T
    | {
        label?: T;
        id?: T;
      };
  stats?:
    | T
    | {
        rating?: T;
        reviewCount?: T;
        experience?: T;
        experienceLabel?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cta-banners_select".
 */
export interface CtaBannersSelect<T extends boolean = true> {
  title?: T;
  headingWhite?: T;
  headingTeal?: T;
  buttonText?: T;
  buttonHref?: T;
  backgroundImage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "values-sections_select".
 */
export interface ValuesSectionsSelect<T extends boolean = true> {
  variant?: T;
  badge?: T;
  heading?: T;
  description?: T;
  ctaLabel?: T;
  ctaHref?: T;
  image?: T;
  values?:
    | T
    | {
        label?: T;
        id?: T;
      };
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        variant?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Global site configuration
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Website name
   */
  siteName: string;
  /**
   * Site logo
   */
  logo?: (number | null) | Media;
  /**
   * Favicon (16x16 or 32x32)
   */
  favicon?: (number | null) | Media;
  /**
   * Contact information
   */
  contact?: {
    /**
     * Phone number
     */
    phone?: string | null;
    /**
     * Email address
     */
    email?: string | null;
    /**
     * Physical address (localized)
     */
    address?: string | null;
  };
  /**
   * Business hours by day
   */
  businessHours?:
    | {
        /**
         * Day or day range
         */
        day: string;
        /**
         * Operating hours
         */
        hours: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Social media links
   */
  socialLinks?:
    | {
        /**
         * Social media platform
         */
        platform: 'facebook' | 'instagram' | 'twitter' | 'linkedin' | 'youtube' | 'tiktok';
        /**
         * Full URL to social profile
         */
        url: string;
        id?: string | null;
      }[]
    | null;
  theme?: {
    /**
     * Main brand color (buttons, links, accents)
     */
    primaryColor?: string | null;
    /**
     * Secondary brand color (headings, dark backgrounds)
     */
    secondaryColor?: string | null;
    /**
     * Accent color for highlights
     */
    accentColor?: string | null;
  };
  footer?: {
    copyright?: string | null;
    /**
     * Footer navigation links
     */
    links?:
      | {
          label: string;
          url: string;
          id?: string | null;
        }[]
      | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Main site navigation menu
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  /**
   * Brand/Logo settings
   */
  brand?: {
    /**
     * Site logo (replaces text brand when set)
     */
    logo?: (number | null) | Media;
    /**
     * Link URL when clicking the logo (default: /)
     */
    logoHref?: string | null;
    /**
     * Brand name (shown when no logo is set)
     */
    name?: string | null;
    /**
     * Tagline shown under brand name
     */
    tagline?: string | null;
  };
  /**
   * Top bar with contact info (desktop only)
   */
  topBar?: {
    show?: boolean | null;
    /**
     * Phone number to display
     */
    phone?: string | null;
    /**
     * Working hours text
     */
    workingHours?: string | null;
    /**
     * Tagline shown on the right side
     */
    tagline?: string | null;
    /**
     * Social media links
     */
    socialLinks?:
      | {
          /**
           * Social media platform
           */
          platform: 'facebook' | 'instagram' | 'twitter' | 'linkedin' | 'youtube' | 'tiktok';
          /**
           * Full URL to social profile
           */
          url: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Dropdowns that auto-populate from a parent page's children
   */
  pageDropdowns?:
    | {
        /**
         * Parent page - its children will populate this dropdown
         */
        parentPage: number | Page;
        /**
         * Override dropdown label (uses parent page title if empty)
         */
        label?: string | null;
        /**
         * Position in navigation (lower = earlier)
         */
        order?: number | null;
        /**
         * Show 'View All' link to parent page at bottom of dropdown
         */
        showViewAll?: boolean | null;
        /**
         * Label for 'View All' link
         */
        viewAllLabel?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Custom dropdown menus with icons and descriptions
   */
  dropdowns?:
    | {
        /**
         * Dropdown trigger label (e.g., 'Services')
         */
        label: string;
        /**
         * Position in navigation (lower = earlier)
         */
        order?: number | null;
        /**
         * Dropdown menu items
         */
        children?:
          | {
              /**
               * Link to a page (label and href auto-filled)
               */
              page?: (number | null) | Page;
              /**
               * Override page title (optional)
               */
              customLabel?: string | null;
              /**
               * Description shown below label
               */
              description?: string | null;
              /**
               * Icon to display
               */
              icon?:
                | (
                    | 'home'
                    | 'building'
                    | 'sparkles'
                    | 'brush'
                    | 'droplets'
                    | 'leaf'
                    | 'shield'
                    | 'clock'
                    | 'star'
                    | 'truck'
                    | 'heart'
                    | 'users'
                    | 'award'
                    | 'message-square'
                  )
                | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Special navigation links (external URLs, anchor links)
   */
  specialLinks?:
    | {
        label: string;
        /**
         * URL (e.g., #contact, https://external.com)
         */
        href: string;
        /**
         * Position in navigation (lower = earlier)
         */
        order?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Call-to-action button in navigation
   */
  cta?: {
    show?: boolean | null;
    label?: string | null;
    href?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Configure the site footer
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  /**
   * Brand information
   */
  brand?: {
    /**
     * Footer logo (optional, shows icon if not set)
     */
    logo?: (number | null) | Media;
    name?: string | null;
    tagline?: string | null;
    description?: string | null;
  };
  /**
   * Footer link columns
   */
  linkGroups?:
    | {
        title: string;
        links?:
          | {
              label: string;
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Contact information
   */
  contact?: {
    /**
     * Phone number
     */
    phone?: string | null;
    /**
     * Email address
     */
    email?: string | null;
    /**
     * Physical address (localized)
     */
    address?: string | null;
  };
  /**
   * Social media links
   */
  socialLinks?:
    | {
        /**
         * Social media platform
         */
        platform: 'facebook' | 'instagram' | 'twitter' | 'linkedin' | 'youtube' | 'tiktok';
        /**
         * Full URL to social profile
         */
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Call-to-action button
   */
  cta?: {
    /**
     * Show the CTA button
     */
    show?: boolean | null;
    /**
     * Button text
     */
    text?: string | null;
    /**
     * Button link
     */
    href?: string | null;
  };
  /**
   * Copyright text (year is added automatically)
   */
  copyright?: string | null;
  /**
   * Bottom bar links (Privacy, Terms, etc.)
   */
  bottomLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Translatable UI text for buttons, labels, and messages
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ui-strings".
 */
export interface UiString {
  id: number;
  common?: {
    readMore?: string | null;
    learnMore?: string | null;
    getStarted?: string | null;
    viewAll?: string | null;
    /**
     * Used as prefix: 'Back to Services'
     */
    backTo?: string | null;
    loading?: string | null;
    error?: string | null;
    tryAgain?: string | null;
  };
  navigation?: {
    home?: string | null;
    about?: string | null;
    services?: string | null;
    contact?: string | null;
    menu?: string | null;
    close?: string | null;
    language?: string | null;
  };
  servicesPage?: {
    badge?: string | null;
    ourServices?: string | null;
    viewDetails?: string | null;
    features?: string | null;
    otherServices?: string | null;
    pricingBadge?: string | null;
    pricingHeading?: string | null;
    pricingSubheading?: string | null;
    mostPopular?: string | null;
    getStarted?: string | null;
    faqBadge?: string | null;
    faqHeading?: string | null;
    faqSubheading?: string | null;
  };
  contactForm?: {
    getInTouch?: string | null;
    sendMessage?: string | null;
    sending?: string | null;
    messageSent?: string | null;
    messageError?: string | null;
    haveAQuestion?: string | null;
  };
  contactPage?: {
    sendUsAMessage?: string | null;
    fillOutForm?: string | null;
    contactInformation?: string | null;
    reachOut?: string | null;
    commonQuestions?: string | null;
    faqSubtitle?: string | null;
    formNotConfigured?: string | null;
    infoNotConfigured?: string | null;
    phone?: string | null;
    email?: string | null;
    address?: string | null;
    businessHours?: string | null;
    followUs?: string | null;
  };
  servicesSection?: {
    badge?: string | null;
    heading?: string | null;
    subheading?: string | null;
    viewAllServices?: string | null;
  };
  aboutPage?: {
    ourTeam?: string | null;
    ourValues?: string | null;
    ourStory?: string | null;
  };
  faq?: {
    badge?: string | null;
    title?: string | null;
    description?: string | null;
    stillHaveQuestions?: string | null;
    noFaqs?: string | null;
  };
  cta?: {
    bookNow?: string | null;
    getQuote?: string | null;
    contactUs?: string | null;
  };
  validation?: {
    required?: string | null;
    invalidEmail?: string | null;
    invalidPhone?: string | null;
  };
  footerStrings?: {
    company?: string | null;
    services?: string | null;
    support?: string | null;
    getInTouch?: string | null;
    callUs?: string | null;
    emailUs?: string | null;
    visitUs?: string | null;
    bookACleaning?: string | null;
    /**
     * Text before heart icon, e.g. 'Made with ❤️ by'
     */
    madeWithLove?: string | null;
    privacyPolicy?: string | null;
    termsOfService?: string | null;
  };
  serviceDetail?: {
    breadcrumbHome?: string | null;
    breadcrumbServices?: string | null;
    professionalService?: string | null;
    startingAt?: string | null;
    bookThisService?: string | null;
    getFreeQuote?: string | null;
    ourServices?: string | null;
    needHelpChoosing?: string | null;
    whatsIncluded?: string | null;
    serviceFeatures?: string | null;
    readyToGetStarted?: string | null;
    /**
     * Use {service} as placeholder for the service name
     */
    bookYourServiceToday?: string | null;
    getFreeEstimate?: string | null;
    callNow?: string | null;
    exploreMore?: string | null;
    relatedServices?: string | null;
    learnMore?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Configure which languages are available on the site
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "languages".
 */
export interface Language {
  id: number;
  /**
   * Languages shown in the language switcher. At least one language must be enabled.
   */
  languages: {
    /**
     * Select a language
     */
    code: 'en' | 'mk' | 'bg' | 'de' | 'fr' | 'es' | 'it' | 'ru' | 'tr' | 'el' | 'ro';
    /**
     * Label shown in the language switcher (e.g., '🇬🇧 English')
     */
    label: string;
    /**
     * Show this language in the language switcher
     */
    enabled?: boolean | null;
    id?: string | null;
  }[];
  /**
   * The default language when no preference is set
   */
  defaultLanguage: 'en' | 'mk' | 'bg' | 'de' | 'fr' | 'es' | 'it' | 'ru' | 'tr' | 'el' | 'ro';
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  logo?: T;
  favicon?: T;
  contact?:
    | T
    | {
        phone?: T;
        email?: T;
        address?: T;
      };
  businessHours?:
    | T
    | {
        day?: T;
        hours?: T;
        id?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  theme?:
    | T
    | {
        primaryColor?: T;
        secondaryColor?: T;
        accentColor?: T;
      };
  footer?:
    | T
    | {
        copyright?: T;
        links?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  brand?:
    | T
    | {
        logo?: T;
        logoHref?: T;
        name?: T;
        tagline?: T;
      };
  topBar?:
    | T
    | {
        show?: T;
        phone?: T;
        workingHours?: T;
        tagline?: T;
        socialLinks?:
          | T
          | {
              platform?: T;
              url?: T;
              id?: T;
            };
      };
  pageDropdowns?:
    | T
    | {
        parentPage?: T;
        label?: T;
        order?: T;
        showViewAll?: T;
        viewAllLabel?: T;
        id?: T;
      };
  dropdowns?:
    | T
    | {
        label?: T;
        order?: T;
        children?:
          | T
          | {
              page?: T;
              customLabel?: T;
              description?: T;
              icon?: T;
              id?: T;
            };
        id?: T;
      };
  specialLinks?:
    | T
    | {
        label?: T;
        href?: T;
        order?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        show?: T;
        label?: T;
        href?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  brand?:
    | T
    | {
        logo?: T;
        name?: T;
        tagline?: T;
        description?: T;
      };
  linkGroups?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  contact?:
    | T
    | {
        phone?: T;
        email?: T;
        address?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        show?: T;
        text?: T;
        href?: T;
      };
  copyright?: T;
  bottomLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ui-strings_select".
 */
export interface UiStringsSelect<T extends boolean = true> {
  common?:
    | T
    | {
        readMore?: T;
        learnMore?: T;
        getStarted?: T;
        viewAll?: T;
        backTo?: T;
        loading?: T;
        error?: T;
        tryAgain?: T;
      };
  navigation?:
    | T
    | {
        home?: T;
        about?: T;
        services?: T;
        contact?: T;
        menu?: T;
        close?: T;
        language?: T;
      };
  servicesPage?:
    | T
    | {
        badge?: T;
        ourServices?: T;
        viewDetails?: T;
        features?: T;
        otherServices?: T;
        pricingBadge?: T;
        pricingHeading?: T;
        pricingSubheading?: T;
        mostPopular?: T;
        getStarted?: T;
        faqBadge?: T;
        faqHeading?: T;
        faqSubheading?: T;
      };
  contactForm?:
    | T
    | {
        getInTouch?: T;
        sendMessage?: T;
        sending?: T;
        messageSent?: T;
        messageError?: T;
        haveAQuestion?: T;
      };
  contactPage?:
    | T
    | {
        sendUsAMessage?: T;
        fillOutForm?: T;
        contactInformation?: T;
        reachOut?: T;
        commonQuestions?: T;
        faqSubtitle?: T;
        formNotConfigured?: T;
        infoNotConfigured?: T;
        phone?: T;
        email?: T;
        address?: T;
        businessHours?: T;
        followUs?: T;
      };
  servicesSection?:
    | T
    | {
        badge?: T;
        heading?: T;
        subheading?: T;
        viewAllServices?: T;
      };
  aboutPage?:
    | T
    | {
        ourTeam?: T;
        ourValues?: T;
        ourStory?: T;
      };
  faq?:
    | T
    | {
        badge?: T;
        title?: T;
        description?: T;
        stillHaveQuestions?: T;
        noFaqs?: T;
      };
  cta?:
    | T
    | {
        bookNow?: T;
        getQuote?: T;
        contactUs?: T;
      };
  validation?:
    | T
    | {
        required?: T;
        invalidEmail?: T;
        invalidPhone?: T;
      };
  footerStrings?:
    | T
    | {
        company?: T;
        services?: T;
        support?: T;
        getInTouch?: T;
        callUs?: T;
        emailUs?: T;
        visitUs?: T;
        bookACleaning?: T;
        madeWithLove?: T;
        privacyPolicy?: T;
        termsOfService?: T;
      };
  serviceDetail?:
    | T
    | {
        breadcrumbHome?: T;
        breadcrumbServices?: T;
        professionalService?: T;
        startingAt?: T;
        bookThisService?: T;
        getFreeQuote?: T;
        ourServices?: T;
        needHelpChoosing?: T;
        whatsIncluded?: T;
        serviceFeatures?: T;
        readyToGetStarted?: T;
        bookYourServiceToday?: T;
        getFreeEstimate?: T;
        callNow?: T;
        exploreMore?: T;
        relatedServices?: T;
        learnMore?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "languages_select".
 */
export interface LanguagesSelect<T extends boolean = true> {
  languages?:
    | T
    | {
        code?: T;
        label?: T;
        enabled?: T;
        id?: T;
      };
  defaultLanguage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}